config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin' unless Rails.env.production?
  # mount Sidekiq::Web => "/sidekiq" unless Rails.env.production?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :channels, only: :none do 
    resources :videos, only: [:show, :index]
  end

  resources :videos, only: :index

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
# == Schema Information
#
# Table name: channels
#
#  id           :bigint           not null, primary key
#  channel_type :string           not null
#  logo_url     :string
#  name         :string           not null
#  slug         :string           not null
#  url          :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  topic_id     :integer
#
# Indexes
#
#  index_channels_on_channel_type  (channel_type)
#  index_channels_on_name          (name)
#  index_channels_on_url           (url) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (topic_id => topics.id)
#
class Channel  < ApplicationRecord
    validates_presence_of :channel_type, :name, :slug

    has_many :videos, dependent: :destroy
    belongs_to :topic
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  status     :string           default("entered"), not null
#  topic_type :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_topics_on_status  (status)
#
class Topic < ApplicationRecord
    validates_presence_of :name, :status

    has_many :channels

    enum status: {
        entered: 'entered',
        processed: 'processed'
    }
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id            :bigint           not null, primary key
#  name          :string           not null
#  recorded_at   :string
#  slug          :string           not null
#  status        :string           default("entered"), not null
#  transcription :jsonb
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  channel_id    :bigint
#  youtube_id    :string           not null
#
# Indexes
#
#  index_videos_on_channel_id  (channel_id)
#  index_videos_on_name        (name)
#  index_videos_on_status      (status)
#  index_videos_on_youtube_id  (youtube_id) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (channel_id => channels.id)
#
class Video < ApplicationRecord
    validates_presence_of :name, :slug, :status, :youtube_id
    belongs_to :channel


    enum status: {
        entered: 'entered',
        download_started: 'download_started',
        download_completed: 'download_completed',
        download_error: 'download_error',
        no_transcript: 'no_transcript',
        transcription_scraped: 'transcription_scraped',
        transcription_scraped_new: 'transcription_scraped_new'
    }

    def watch_url
        "https://www.youtube.com/watch?v=#{youtube_id}"
    end

    def embed_url
        "https://www.youtube.com/embed/#{youtube_id}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def index
        @videos = Video
            .transcription_scraped
            .includes(:channel)

        @videos = @videos
            .where(channels: { slug: params[:channel_id]}) if params[:channel_id]

        if params[:query]
            # search_terms = params.require(:query).gsub(/[^0-9a-z ]/i, '').split(' ')[0..10]
            @videos = @videos
                .where("name ILIKE ?", "%#{params[:query]}%")
                .or(@videos
                    .where("transcription->>'title' ILIKE ?", "%#{params[:query]}%")    
                )
        end
            
        @videos = @videos.paginate(page: params[:page])
    end

    def show
        @video = Video
            .includes(:channel)
            .transcription_scraped
            .where(channels: { slug: params.require(:channel_id)})
            .find_by!(slug: params.require(:id))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.erb
<div class="container mt-5">
    <div class="jumbotron">
        <h1 class="display-3 text-center">Find the right video on YouTube by the words from their transcripts!</h1>
        <hr class="my-4">
        <%= render 'shared/search_form' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= display_meta_tags site: 'You Transcribe' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script data-ad-client="ca-pub-6348836384472381" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag 'you_transcribe_logo.png', class: 'navbar-brand-image', width: 250, height: 62 %>
      <% end %>
    </nav>
    <main class="main">
      <%= yield %>
    </main>
    <footer class="footer p-3 text-center">
      <%= link_to 'All Videos', videos_path %>
      <% if @video.present? %>
       |
        <%= link_to "All videos on #{@video.channel.name}", channel_videos_path(@video.channel.slug) %>
      <% end %>
    </footer>
  </body>
</html>

app/views/shared/_search_form.html.erb
<%= form_with url: videos_path, method: :get do |f| %>
    <div class="row">
        <div class="col-xl-11 col-sm-10">
            <%= f.text_field :query, class: 'form-control', placeholder: 'Search', value: params[:query] %>
        </div>
        <div class="col-xl-1 col-sm-2">
            <%= f.submit 'Search', class: 'btn btn-primary' %>
        </div>
    </div>
<% end %>

app/views/videos/_video.html.erb
<div class="card p-3 m-3">
    <div class="row">
        <div class="col-4">
            <%= link_to video.channel.url, target: :blank do  %>
                <%= image_tag video.channel.logo_url, width: 88, height: 88 %>
                <p class="mt-2">
                    <%= video.channel.name %>
                </p>
            <% end %>
        </div>
        <div class="col-4">
            <%= link_to video.name, channel_video_path(video.channel.slug, video.slug) %>
        </div>
        <div class="col-4">
            <% video.transcription[0..5].each do |transcription_line| %>
                <div><%= transcription_line['text'] %></div>
            <% end %>
            <p>...</p>
        </div>
    </div>
</div>

app/views/videos/index.html.erb
<div class="container">
    <div class="mt-3 mx-3">
        <%= render 'shared/search_form' %>
    </div>
    <%= render @videos %>
    <% unless @videos.present? %>
        <div class="alert alert-warning mt-3">
            <h4 class="alert-heading">Sorry, nothing was found!</h4>
            <p class="mb-0"> We constantly index YouTube videos but so far we didn't come across what you are looking for! </p>
        </div>
    <% end %>
    <div class="d-flex justify-content-center">
        <%= will_paginate @videos, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>

app/views/videos/show.html.erb
<% description @video.name %>
<% title @video.name %>
<div class="page">
    <div class="channel">
        <div> 
            <img src=<%= @video.channel.logo_url %> alt="Channel Logo URL" class="channel-logo" width="88" height="88" >
        </div>
        <h1><%= link_to @video.channel.name, @video.channel.url %> </h1>
    </div>
    <iframe src="<%= @video.embed_url %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

    <div class="container my-2 transcription-container">
        <h2 class="video-name"><%= @video.name %></h2>
        <div class="transcription">
            <% @video.transcription.each do |transcription_line| %>
                <div class="row">
                    <div class="col-2">
                        <%= transcription_line['offset'] %>
                    </div>
                    <div class="col-10"> 
                        <%= transcription_line['text'] %>
                    </div>
                </div>
             <% end %>
        </div>
    </div>
</div>